import { Platform, StyleSheet } from 'react-native';
import { colors, radius, shadow } from './theme';

export const mainStyles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.ink },
  shell: { flex: 1, flexDirection: 'row' },
  main: { flex: 1, backgroundColor: colors.inkSoft, minWidth: 0 },

  sidebar: { width: 244, backgroundColor: colors.ink, borderRightWidth: 1, borderRightColor: colors.line, padding: 24 },
  sidebarNav: { gap: 7, marginTop: 48 },

  sidebarItem: { minHeight: 50, borderRadius: 15, flexDirection: 'row', alignItems: 'center', paddingHorizontal: 8, gap: 11 },
  sidebarItemActive: { backgroundColor: colors.panel },
  sidebarIcon: { width: 34, height: 34, borderRadius: 11, alignItems: 'center', justifyContent: 'center' },
  sidebarIconActive: { backgroundColor: colors.lime },
  sidebarLabel: { color: colors.textMuted, fontSize: 14, fontWeight: '700', flex: 1 },
  sidebarLabelActive: { color: colors.text, fontWeight: '900' },
  navBadge: { minWidth: 22, height: 22, borderRadius: 8, backgroundColor: colors.coral, alignItems: 'center', justifyContent: 'center' },
  navBadgeText: { color: colors.white, fontSize: 10, fontWeight: '900' },

  sidebarBottom: { marginTop: 'auto', gap: 14 },
  sidebarCaption: { color: colors.textDim, fontSize: 9, fontWeight: '900', letterSpacing: 1.4 },
  sidebarProviders: { flexDirection: 'row', flexWrap: 'wrap', gap: 7 },
  noConnections: { color: colors.textDim, fontSize: 11 },
  logout: { flexDirection: 'row', gap: 10, alignItems: 'center', paddingVertical: 12, borderTopWidth: 1, borderTopColor: colors.line, marginTop: 8 },
  logoutText: { color: colors.textMuted, fontSize: 12, fontWeight: '700' },

  appHeader: { height: 72, borderBottomWidth: 1, borderBottomColor: colors.line, paddingHorizontal: 26, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: colors.inkSoft, zIndex: 3 },
  headerContext: { flex: 1 },
  locationChip: { alignSelf: 'flex-start', flexDirection: 'row', alignItems: 'center', gap: 6, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.panel, borderRadius: 12, paddingHorizontal: 11, paddingVertical: 7 },
  locationFlag: { color: colors.lime, fontSize: 9, fontWeight: '900', letterSpacing: 0.8 },
  locationText: { color: colors.textMuted, fontSize: 11, fontWeight: '800' },
  headerActions: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  headerAvatarButton: { borderRadius: radius.pill },
  headerPressed: { opacity: 0.7, transform: [{ scale: 0.97 }] },

  mobileNav: { height: Platform.OS === 'ios' ? 82 : 69, paddingBottom: Platform.OS === 'ios' ? 14 : 5, flexDirection: 'row', borderTopWidth: 1, borderTopColor: colors.line, backgroundColor: colors.ink, zIndex: 10 },
  mobileNavItem: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 2 },
  mobileNavIcon: { width: 35, height: 31, alignItems: 'center', justifyContent: 'center', borderRadius: 12 },
  mobileNavIconActive: { backgroundColor: colors.lime },
  mobileNavLabel: { color: colors.textDim, fontSize: 8, fontWeight: '700' },
  mobileNavLabelActive: { color: colors.text, fontWeight: '900' },

  screen: { flex: 1 },
  screenContent: { width: '100%', maxWidth: 1440, alignSelf: 'center', paddingHorizontal: 26, paddingTop: 30, paddingBottom: 70 },

  pageTitleWrap: { marginBottom: 24, flex: 1 },
  pageEyebrow: { color: colors.lime, fontSize: 10, fontWeight: '900', letterSpacing: 1.6, marginBottom: 7 },
  pageTitle: { color: colors.text, fontSize: 31, lineHeight: 37, fontWeight: '900', letterSpacing: -1 },
  pageDescription: { color: colors.textMuted, fontSize: 13, lineHeight: 20, marginTop: 7, maxWidth: 680 },

  homeHero: { minHeight: 510, borderRadius: radius.xl, overflow: 'hidden', marginBottom: 34, backgroundColor: colors.panel, ...shadow },
  homeHeroWide: { minHeight: 470 },
  homeHeroImage: { flex: 1 },
  homeHeroRadius: { borderRadius: radius.xl },
  homeHeroGradient: { flex: 1, justifyContent: 'center', padding: 32 },
  heroInfo: { maxWidth: 590 },
  heroBadges: { flexDirection: 'row', gap: 8, marginBottom: 13 },
  heroMatch: { backgroundColor: colors.lime, color: colors.ink, borderRadius: 8, paddingHorizontal: 9, paddingVertical: 5, fontSize: 9, fontWeight: '900', overflow: 'hidden' },
  heroPremiere: { backgroundColor: 'rgba(7,10,18,0.8)', color: colors.text, borderRadius: 8, paddingHorizontal: 9, paddingVertical: 5, fontSize: 9, fontWeight: '900', overflow: 'hidden', borderWidth: 1, borderColor: colors.line },
  heroTitle: { color: colors.white, fontSize: 43, lineHeight: 47, fontWeight: '900', letterSpacing: -1.5 },
  heroSubtitle: { color: '#E7EAF0', fontSize: 15, fontWeight: '700', marginTop: 5 },
  heroMeta: { flexDirection: 'row', alignItems: 'center', gap: 12, marginTop: 15 },
  heroMetaText: { color: '#D7DDE7', fontSize: 12, fontWeight: '700' },
  heroSynopsis: { color: colors.textMuted, fontSize: 13, lineHeight: 20, marginTop: 14 },
  heroActions: { flexDirection: 'row', gap: 10, marginTop: 21, flexWrap: 'wrap' },
  heroPrimary: { minWidth: 150 },
  heroSecondary: { minWidth: 165 },
  friendSignal: { flexDirection: 'row', alignItems: 'center', gap: 10, marginTop: 20 },
  avatarPile: { flexDirection: 'row', width: 45 },
  piledAvatar: { marginLeft: -8 },
  friendSignalText: { color: colors.textMuted, fontSize: 11, fontWeight: '600' },

  dashboardGrid: { gap: 28, marginBottom: 30 },
  dashboardGridWide: { flexDirection: 'row' },
  dashboardMain: { flex: 1 },
  dashboardMainWide: { flex: 1.65, minWidth: 0 },
  dashboardSide: { flex: 1 },
  dashboardSideWide: { maxWidth: 360 },
  posterRow: { paddingRight: 12 },

  watchTogetherCard: { backgroundColor: colors.panel, borderWidth: 1, borderColor: colors.line, borderRadius: radius.lg, padding: 20, minHeight: 240 },
  watchTogetherTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  roomIcon: { width: 44, height: 44, borderRadius: 15, backgroundColor: 'rgba(200,255,90,0.1)', alignItems: 'center', justifyContent: 'center' },
  livePill: { flexDirection: 'row', alignItems: 'center', gap: 6, paddingHorizontal: 9, paddingVertical: 6, borderRadius: 9, backgroundColor: 'rgba(98,217,159,0.1)' },
  liveSmall: { width: 6, height: 6, borderRadius: 3, backgroundColor: colors.success },
  liveText: { color: colors.success, fontSize: 8, fontWeight: '900', letterSpacing: 0.8 },
  watchTogetherTitle: { color: colors.text, fontSize: 19, fontWeight: '900', marginTop: 16 },
  watchTogetherText: { color: colors.textMuted, fontSize: 12, lineHeight: 18, marginTop: 7 },
  watchPeople: { flexDirection: 'row', alignItems: 'center', marginVertical: 17 },
  watchLine: { height: 1, backgroundColor: colors.line, width: 38, marginHorizontal: 5 },
  addPerson: { width: 38, height: 38, borderRadius: 19, borderWidth: 1, borderStyle: 'dashed', borderColor: colors.textDim, alignItems: 'center', justifyContent: 'center' },

  insightCard: { backgroundColor: colors.panel, borderRadius: radius.lg, borderWidth: 1, borderColor: colors.line, padding: 20, flexDirection: 'row', alignItems: 'center', gap: 15, flexWrap: 'wrap' },
  insightIcon: { width: 46, height: 46, borderRadius: 15, backgroundColor: colors.lime, alignItems: 'center', justifyContent: 'center' },
  insightCopy: { flex: 1, minWidth: 220 },
  insightTitle: { color: colors.text, fontSize: 15, fontWeight: '900' },
  insightText: { color: colors.textMuted, fontSize: 11, lineHeight: 17, marginTop: 4 },
  insightStats: { flexDirection: 'row', gap: 16, alignItems: 'center' },
  statDivider: { width: 1, height: 35, backgroundColor: colors.line },

  discoverContent: { flexGrow: 1, width: '100%', maxWidth: 1200, alignSelf: 'center', paddingHorizontal: 24, paddingTop: 30, paddingBottom: 60 },
  discoverHeader: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', gap: 20 },
  discoverCounter: { backgroundColor: colors.panel, borderWidth: 1, borderColor: colors.line, borderRadius: 15, paddingHorizontal: 17, paddingVertical: 11, alignItems: 'center' },
  discoverCounterValue: { color: colors.lime, fontSize: 20, fontWeight: '900' },
  discoverCounterLabel: { color: colors.textMuted, fontSize: 9, fontWeight: '700' },
  discoverModeTabs: { alignSelf: 'flex-start', flexDirection: 'row', flexWrap: 'wrap', backgroundColor: colors.panel, borderWidth: 1, borderColor: colors.line, borderRadius: 15, padding: 4, marginBottom: 22 },
  discoverModeTab: { minHeight: 42, borderRadius: 11, paddingHorizontal: 14, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 7 },
  discoverModeTabActive: { backgroundColor: colors.lime },
  discoverModeText: { color: colors.textMuted, fontSize: 11, fontWeight: '800' },
  discoverModeTextActive: { color: colors.ink },
  newBadge: { backgroundColor: colors.coral, borderRadius: 7, paddingHorizontal: 5, paddingVertical: 3 },
  newBadgeText: { color: colors.white, fontSize: 6, fontWeight: '900', letterSpacing: 0.6 },
  filterRow: { gap: 8, paddingBottom: 25 },
  deckArea: { alignItems: 'center', minHeight: 712 },
  gestureLegend: { flexDirection: 'row', justifyContent: 'center', flexWrap: 'wrap', gap: 20, marginTop: 4 },
  legendItem: { flexDirection: 'row', alignItems: 'center', gap: 5 },
  legendText: { color: colors.textDim, fontSize: 10, fontWeight: '700' },
  toast: { position: 'absolute', top: 25, alignSelf: 'center', backgroundColor: colors.panelRaised, borderWidth: 1, borderColor: colors.line, borderRadius: 14, paddingHorizontal: 16, paddingVertical: 11, flexDirection: 'row', alignItems: 'center', gap: 8, ...shadow },
  toastText: { color: colors.text, fontSize: 12, fontWeight: '800' },

  rouletteContent: { flexGrow: 1, width: '100%', maxWidth: 1280, alignSelf: 'center', paddingHorizontal: 26, paddingTop: 30, paddingBottom: 70 },
  rouletteHeader: { flexDirection: 'row', alignItems: 'flex-start', gap: 18, flexWrap: 'wrap' },
  rouletteHeaderCompact: { flexDirection: 'column', alignItems: 'stretch', gap: 0 },
  antiViralBadge: { flexDirection: 'row', alignItems: 'center', gap: 7, borderRadius: 12, backgroundColor: 'rgba(200,255,90,0.08)', borderWidth: 1, borderColor: 'rgba(200,255,90,0.22)', paddingHorizontal: 12, paddingVertical: 9 },
  antiViralText: { color: colors.lime, fontSize: 9, fontWeight: '900', letterSpacing: 1.1 },
  rouletteLayout: { flexDirection: 'row', alignItems: 'flex-start', gap: 30 },
  rouletteLayoutCompact: { flexDirection: 'column', alignItems: 'stretch' },
  wheelColumn: { flex: 0.85, minWidth: 300, alignItems: 'center' },
  wheelFrame: { alignItems: 'center', justifyContent: 'center', position: 'relative', marginTop: 12 },
  rouletteWheel: { position: 'relative', backgroundColor: colors.panel, borderWidth: 2, borderColor: colors.lime, overflow: 'hidden', ...shadow },
  wheelOrbitOne: { position: 'absolute', left: '12%', right: '12%', top: '12%', bottom: '12%', borderRadius: 999, borderWidth: 1, borderColor: 'rgba(111,168,255,0.28)' },
  wheelOrbitTwo: { position: 'absolute', left: '28%', right: '28%', top: '28%', bottom: '28%', borderRadius: 999, borderWidth: 1, borderColor: 'rgba(200,255,90,0.24)' },
  wheelPointer: { position: 'absolute', zIndex: 5, top: -7, width: 42, height: 35, borderBottomLeftRadius: 14, borderBottomRightRadius: 14, backgroundColor: colors.lime, alignItems: 'center', justifyContent: 'center' },
  wheelNode: { position: 'absolute', width: 62, height: 62, borderRadius: 31, backgroundColor: colors.panelRaised, borderWidth: 1, borderColor: colors.line, alignItems: 'center', justifyContent: 'center', padding: 5 },
  wheelNodeActive: { backgroundColor: colors.lime, borderColor: colors.lime },
  wheelNodeText: { color: colors.text, fontSize: 7, lineHeight: 9, fontWeight: '800', marginTop: 3, maxWidth: 52 },
  wheelNodeTextActive: { color: colors.ink },
  wheelHub: { position: 'absolute', width: 104, height: 104, borderRadius: 52, backgroundColor: colors.ink, borderWidth: 5, borderColor: colors.panelRaised, alignItems: 'center', justifyContent: 'center', ...shadow },
  wheelHubMark: { color: colors.ink, backgroundColor: colors.lime, width: 36, height: 36, borderRadius: 12, overflow: 'hidden', textAlign: 'center', textAlignVertical: 'center', fontSize: 21, fontWeight: '900' },
  wheelHubText: { color: colors.text, fontSize: 8, fontWeight: '900', letterSpacing: 1.3, marginTop: 5 },
  spinButton: { width: '100%', maxWidth: 320, marginTop: 24 },
  tasteProfile: { width: '100%', maxWidth: 420, alignItems: 'center', marginTop: 18 },
  tasteProfileLabel: { color: colors.textDim, fontSize: 9, fontWeight: '900', letterSpacing: 1.3, marginBottom: 8 },
  tasteProfilePills: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'center', gap: 7 },
  rouletteResultCard: { flex: 1.15, minWidth: 320, backgroundColor: colors.panel, borderWidth: 1, borderColor: colors.line, borderRadius: radius.xl, overflow: 'hidden', ...shadow },
  rouletteResultImage: { height: 330 },
  rouletteResultImageRadius: { borderTopLeftRadius: radius.xl, borderTopRightRadius: radius.xl },
  rouletteResultGradient: { flex: 1, justifyContent: 'space-between', padding: 22 },
  hiddenGemPill: { alignSelf: 'flex-start', flexDirection: 'row', alignItems: 'center', gap: 6, borderRadius: 9, backgroundColor: colors.lime, paddingHorizontal: 9, paddingVertical: 6 },
  hiddenGemPillText: { color: colors.ink, fontSize: 8, fontWeight: '900', letterSpacing: 0.7 },
  rouletteMatch: { color: colors.lime, fontSize: 10, fontWeight: '900', letterSpacing: 1.4 },
  rouletteResultTitle: { color: colors.white, fontSize: 35, lineHeight: 39, fontWeight: '900', letterSpacing: -1, marginTop: 5 },
  rouletteResultSubtitle: { color: '#E5E9F0', fontSize: 13, fontWeight: '700', marginTop: 4 },
  rouletteResultBody: { padding: 20 },
  rouletteMeta: { flexDirection: 'row', alignItems: 'center', flexWrap: 'wrap', gap: 9, marginBottom: 15 },
  rouletteMetaText: { color: colors.textMuted, fontSize: 10, fontWeight: '800' },
  rouletteReason: { flexDirection: 'row', alignItems: 'flex-start', gap: 10, borderTopWidth: 1, borderTopColor: colors.line, paddingVertical: 13 },
  rouletteReasonCopy: { flex: 1 },
  rouletteReasonTitle: { color: colors.text, fontSize: 11, fontWeight: '900' },
  rouletteReasonText: { color: colors.textMuted, fontSize: 10, lineHeight: 15, marginTop: 3 },
  editorialSignal: { color: colors.blue, fontSize: 10, lineHeight: 15, fontWeight: '700', backgroundColor: 'rgba(111,168,255,0.08)', borderRadius: 11, padding: 11 },
  rouletteActions: { flexDirection: 'row', gap: 9, marginTop: 16, flexWrap: 'wrap' },
  rouletteAction: { flex: 1, minWidth: 150 },
  rouletteMethod: { flexDirection: 'row', flexWrap: 'wrap', gap: 13, marginTop: 28 },
  methodCard: { flex: 1, minWidth: 220, backgroundColor: colors.panel, borderWidth: 1, borderColor: colors.line, borderRadius: radius.lg, padding: 17 },
  methodNumber: { color: colors.lime, fontSize: 22, fontWeight: '900' },
  methodPenalty: { color: colors.coral },
  methodTitle: { color: colors.text, fontSize: 12, fontWeight: '900', marginTop: 6 },
  methodText: { color: colors.textMuted, fontSize: 10, lineHeight: 15, marginTop: 4 },

  forumTitleRow: { flexDirection: 'row', alignItems: 'center', gap: 20, flexWrap: 'wrap' },
  forumTitleRowCompact: { flexDirection: 'column', alignItems: 'stretch', gap: 0 },
  forumCreateMobile: { width: '100%', marginBottom: 20 },
  forumToolbar: { flexDirection: 'row', gap: 14, alignItems: 'center', marginBottom: 20, flexWrap: 'wrap' },
  forumTabs: { flexDirection: 'row', borderWidth: 1, borderColor: colors.line, backgroundColor: colors.panel, borderRadius: 15, padding: 4 },
  forumTab: { minHeight: 41, borderRadius: 11, paddingHorizontal: 15, flexDirection: 'row', alignItems: 'center', gap: 8 },
  forumTabActive: { backgroundColor: colors.lime },
  forumTabText: { color: colors.textMuted, fontSize: 12, fontWeight: '800' },
  forumTabTextActive: { color: colors.ink },
  searchBox: { flex: 1, minWidth: 230, maxWidth: 430, height: 50, borderRadius: 15, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.panel, flexDirection: 'row', alignItems: 'center', paddingHorizontal: 14, gap: 9 },
  searchInput: { flex: 1, color: colors.text, fontSize: 13, outlineStyle: 'none' } as any,
  identifyInfo: { backgroundColor: 'rgba(111,168,255,0.08)', borderWidth: 1, borderColor: 'rgba(111,168,255,0.2)', borderRadius: radius.md, padding: 15, flexDirection: 'row', gap: 12, marginBottom: 18 },
  identifyIcon: { width: 39, height: 39, borderRadius: 13, backgroundColor: 'rgba(111,168,255,0.12)', alignItems: 'center', justifyContent: 'center' },
  identifyCopy: { flex: 1 },
  identifyTitle: { color: colors.text, fontSize: 13, fontWeight: '900' },
  identifyText: { color: colors.textMuted, fontSize: 11, lineHeight: 17, marginTop: 3 },

  topicGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 14 },
  topicCard: { flexGrow: 1, width: '48%', minWidth: 310, backgroundColor: colors.panel, borderWidth: 1, borderColor: colors.line, borderRadius: radius.lg, padding: 18 },
  topicCardHighlighted: { borderColor: colors.lime, backgroundColor: 'rgba(200,255,90,0.06)' },
  cardPressed: { opacity: 0.75 },
  topicTop: { flexDirection: 'row', alignItems: 'center', marginBottom: 15 },
  topicAuthor: { flex: 1, marginLeft: 10 },
  topicAuthorName: { color: colors.text, fontSize: 12, fontWeight: '900' },
  topicTime: { color: colors.textDim, fontSize: 10, marginTop: 2 },
  solvedPill: { flexDirection: 'row', alignItems: 'center', gap: 5, paddingHorizontal: 8, paddingVertical: 5, borderRadius: 8, backgroundColor: 'rgba(111,168,255,0.08)' },
  solvedPillActive: { backgroundColor: colors.lime },
  solvedText: { color: colors.blue, fontSize: 9, fontWeight: '900' },
  solvedTextActive: { color: colors.ink },
  topicTitle: { color: colors.text, fontSize: 18, lineHeight: 23, fontWeight: '900' },
  topicBody: { color: colors.textMuted, fontSize: 12, lineHeight: 19, marginTop: 8 },
  topicTags: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginTop: 14 },
  topicFooter: { borderTopWidth: 1, borderTopColor: colors.line, paddingTop: 13, marginTop: 15, flexDirection: 'row', alignItems: 'center', gap: 13 },
  topicMetric: { flexDirection: 'row', alignItems: 'center', gap: 5 },
  topicMetricText: { color: colors.textMuted, fontSize: 10 },
  topicOpen: { marginLeft: 'auto', flexDirection: 'row', alignItems: 'center', gap: 5 },
  topicOpenText: { color: colors.lime, fontSize: 10, fontWeight: '800' },
  topicDetailHeading: { flex: 1 },
  topicDetailAuthor: { flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 17 },
  topicDetailBody: { color: colors.text, fontSize: 14, lineHeight: 22 },
  topicDetailStats: { flexDirection: 'row', gap: 18, borderTopWidth: 1, borderTopColor: colors.line, borderBottomWidth: 1, borderBottomColor: colors.line, paddingVertical: 14, marginTop: 17 },
  topicDetailReply: { backgroundColor: colors.inkSoft, borderRadius: radius.md, padding: 15, marginTop: 17 },
  topicDetailReplyLabel: { color: colors.lime, fontSize: 8, fontWeight: '900', letterSpacing: 1.2 },
  topicDetailReplyText: { color: colors.textMuted, fontSize: 11, lineHeight: 17, marginTop: 7 },
  topicDetailReplyAuthor: { color: colors.textDim, fontSize: 9, marginTop: 9 },
  topicReplyButton: { marginTop: 15 },

  emptyState: { alignItems: 'center', paddingVertical: 60 },
  emptyTitle: { color: colors.text, fontSize: 17, fontWeight: '900', marginTop: 13 },
  emptyText: { color: colors.textMuted, fontSize: 12, marginTop: 6 },

  modalBackdrop: { flex: 1, backgroundColor: 'rgba(0,0,0,0.76)', alignItems: 'center', justifyContent: 'center', padding: 18 },
  composeModal: { width: '100%', maxWidth: 620, maxHeight: '92%', backgroundColor: colors.panel, borderRadius: radius.xl, borderWidth: 1, borderColor: colors.line, padding: 24, ...shadow },
  modalHeader: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', gap: 15, marginBottom: 22 },
  modalEyebrow: { color: colors.lime, fontSize: 9, fontWeight: '900', letterSpacing: 1.5, marginBottom: 5 },
  modalTitle: { color: colors.text, fontSize: 24, fontWeight: '900' },
  inputLabel: { color: colors.textMuted, fontSize: 11, fontWeight: '800', marginBottom: 7, marginTop: 3 },
  modalInput: { minHeight: 50, borderRadius: 14, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.inkSoft, color: colors.text, fontSize: 13, paddingHorizontal: 14, paddingVertical: 12, marginBottom: 15, outlineStyle: 'none' } as any, modalTextarea: { minHeight: 130, textAlignVertical: 'top' },
  modalTextareaSmall: { minHeight: 90, textAlignVertical: 'top' },
  composeTips: { flexDirection: 'row', gap: 8, alignItems: 'flex-start', backgroundColor: 'rgba(98,217,159,0.07)', borderRadius: 12, padding: 11 },
  composeTipsText: { flex: 1, color: colors.textMuted, fontSize: 10, lineHeight: 15 },
  modalActions: { flexDirection: 'row', gap: 10, marginTop: 18 },
  modalAction: { flex: 1 },

  friendsModeTabs: { alignSelf: 'flex-start', flexDirection: 'row', flexWrap: 'wrap', backgroundColor: colors.panel, borderWidth: 1, borderColor: colors.line, borderRadius: 15, padding: 4, marginBottom: 18 },
  friendsModeTab: { minHeight: 42, borderRadius: 11, paddingHorizontal: 15, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 7 },
  friendsModeTabActive: { backgroundColor: colors.lime },
  friendsModeText: { color: colors.textMuted, fontSize: 11, fontWeight: '800' },
  friendsModeTextActive: { color: colors.ink },
  friendsLayout: { flexDirection: 'row', flexWrap: 'wrap', gap: 20 },
  friendsPanel: { flex: 1.1, minWidth: 310, backgroundColor: colors.panel, borderWidth: 1, borderColor: colors.line, borderRadius: radius.lg, padding: 20 },
  roomPanel: { flex: 0.9, minWidth: 310, minHeight: 650, backgroundColor: colors.panel, borderWidth: 1, borderColor: colors.line, borderRadius: radius.lg, padding: 20 },
  messagePanel: { padding: 0, overflow: 'hidden' },
  friendList: { marginTop: 13, gap: 6 },
  friendRow: { minHeight: 70, borderRadius: radius.md, padding: 10, flexDirection: 'row', alignItems: 'center', gap: 11, borderWidth: 1, borderColor: 'transparent' },
  friendRowSelected: { backgroundColor: 'rgba(200,255,90,0.06)', borderColor: 'rgba(200,255,90,0.16)' },
  friendCopy: { flex: 1, minWidth: 0 },
  friendName: { color: colors.text, fontSize: 13, fontWeight: '900' },
  friendStatus: { color: colors.textMuted, fontSize: 10, marginTop: 4 },
  compatibility: { alignItems: 'flex-end' },
  compatibilityValue: { color: colors.lime, fontSize: 13, fontWeight: '900' },
  compatibilityLabel: { color: colors.textDim, fontSize: 8, textTransform: 'uppercase' },
  friendSelect: { width: 30, height: 30, borderRadius: 10, borderWidth: 1, borderColor: colors.line, alignItems: 'center', justifyContent: 'center' },
  friendSelectActive: { backgroundColor: colors.lime, borderColor: colors.lime },
  suggestionCard: { marginTop: 15, borderTopWidth: 1, borderTopColor: colors.line, paddingTop: 15 },
  suggestionLabel: { color: colors.textDim, fontSize: 9, fontWeight: '900', letterSpacing: 1.2 },
  suggestedFriendRow: { minHeight: 74, flexDirection: 'row', alignItems: 'center', gap: 11, marginTop: 8 },
  directChat: { flex: 1, minHeight: 648 },
  directChatHeader: { minHeight: 78, paddingHorizontal: 18, flexDirection: 'row', alignItems: 'center', gap: 12, borderBottomWidth: 1, borderBottomColor: colors.line },
  directChatHeaderCopy: { flex: 1 },
  directChatName: { color: colors.text, fontSize: 14, fontWeight: '900' },
  directChatPresence: { color: colors.success, fontSize: 9, fontWeight: '700', marginTop: 4 },
  videoInviteButton: { width: 40, height: 40, borderRadius: 13, backgroundColor: 'rgba(200,255,90,0.08)', borderWidth: 1, borderColor: 'rgba(200,255,90,0.16)', alignItems: 'center', justifyContent: 'center' },
  directMessagesScroll: { flex: 1, minHeight: 430, maxHeight: 510 },
  directMessagesContent: { flexGrow: 1, justifyContent: 'flex-end', padding: 16, gap: 10 },
  messageRow: { flexDirection: 'row', alignItems: 'flex-end', gap: 7, alignSelf: 'flex-start', maxWidth: '88%' },
  messageRowMine: { alignSelf: 'flex-end', justifyContent: 'flex-end' },
  messageBubble: { borderRadius: 16, paddingHorizontal: 12, paddingVertical: 9, minWidth: 78 },
  messageBubbleFriend: { backgroundColor: colors.panelRaised, borderBottomLeftRadius: 5 },
  messageBubbleMine: { backgroundColor: colors.lime, borderBottomRightRadius: 5 },
  messageText: { color: colors.text, fontSize: 11, lineHeight: 16 },
  messageTextMine: { color: colors.ink, fontWeight: '700' },
  messageMeta: { flexDirection: 'row', alignItems: 'center', justifyContent: 'flex-end', gap: 4, marginTop: 5 },
  messageTime: { color: colors.textDim, fontSize: 8 },
  messageTimeMine: { color: 'rgba(7,10,18,0.65)' },
  messageComposer: { minHeight: 72, padding: 12, borderTopWidth: 1, borderTopColor: colors.line, flexDirection: 'row', alignItems: 'center', gap: 8 },
  messageInput: { flex: 1, minHeight: 44, maxHeight: 100, borderRadius: 13, backgroundColor: colors.inkSoft, borderWidth: 1, borderColor: colors.line, color: colors.text, paddingHorizontal: 13, fontSize: 11, outlineStyle: 'none' } as any,
  messageSendButton: { width: 44, height: 44, borderRadius: 13, backgroundColor: colors.lime, alignItems: 'center', justifyContent: 'center' },
  messageSendButtonDisabled: { opacity: 0.35 },
  chatEmpty: { flex: 1, minHeight: 200, alignItems: 'center', justifyContent: 'center', padding: 24 },
  chatEmptyTitle: { color: colors.text, fontSize: 14, fontWeight: '900', marginTop: 11, textAlign: 'center' },
  chatEmptyText: { color: colors.textMuted, fontSize: 10, lineHeight: 15, marginTop: 5, textAlign: 'center' },

  roomEmpty: { flex: 1, justifyContent: 'center' },
  roomArt: { height: 160, borderRadius: radius.lg, marginBottom: 22, alignItems: 'center', justifyContent: 'center', overflow: 'hidden' },
  roomArtCore: { width: 64, height: 64, borderRadius: 32, backgroundColor: colors.lime, alignItems: 'center', justifyContent: 'center' },
  roomOrbit: { position: 'absolute' },
  roomOrbitOne: { top: 24, left: 50 },
  roomOrbitTwo: { bottom: 24, right: 50 },
  roomEmptyTitle: { color: colors.text, fontSize: 22, fontWeight: '900', textAlign: 'center' },
  roomEmptyText: { color: colors.textMuted, fontSize: 12, lineHeight: 19, textAlign: 'center', marginTop: 8, marginBottom: 17 },
  selectedPeople: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'center', gap: 7, marginBottom: 18 },
  selectedPerson: { flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: colors.panelRaised, borderRadius: 20, padding: 4, paddingRight: 9 },
  selectedName: { color: colors.text, fontSize: 10, fontWeight: '800' },
  legalNote: { color: colors.textDim, fontSize: 9, textAlign: 'center', marginTop: 11 },

  activeRoom: { flex: 1 },
  activeRoomTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 10, marginBottom: 15 },
  roomKicker: { color: colors.lime, fontSize: 8, fontWeight: '900', letterSpacing: 1.2 },
  activeRoomTitle: { color: colors.text, fontSize: 20, fontWeight: '900', marginTop: 4 },
  roomPlayer: { height: 250 },
  roomPlayerRadius: { borderRadius: radius.lg },
  roomPlayerOverlay: { flex: 1, alignItems: 'center', justifyContent: 'center', borderRadius: radius.lg },
  playButton: { width: 62, height: 62, borderRadius: 31, backgroundColor: colors.lime, alignItems: 'center', justifyContent: 'center' },
  playerBottom: { position: 'absolute', left: 15, right: 15, bottom: 14 },
  progressTrack: { height: 4, borderRadius: 2, backgroundColor: 'rgba(255,255,255,0.25)' },
  progressFill: { height: '100%', backgroundColor: colors.lime, borderRadius: 2 },
  timeRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 7 },
  timeText: { color: colors.white, fontSize: 9, fontWeight: '700' },
  syncText: { color: colors.success, fontSize: 9, fontWeight: '800' },
  playerControls: { flexDirection: 'row', gap: 8, alignItems: 'center', marginVertical: 12 },
  playerMainControl: { flex: 1 },
  chatBox: { borderWidth: 1, borderColor: colors.line, borderRadius: radius.md, backgroundColor: colors.inkSoft, padding: 12, marginBottom: 12 },
  roomChatHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 8 },
  roomChatTitle: { color: colors.text, fontSize: 11, fontWeight: '900' },
  roomChatCount: { color: colors.textDim, fontSize: 8 },
  roomMessagesScroll: { maxHeight: 170, minHeight: 100 },
  roomMessagesContent: { justifyContent: 'flex-end', gap: 8, paddingVertical: 5 },
  chatInputRow: { flexDirection: 'row', gap: 7 },
  chatInput: { flex: 1, minHeight: 39, borderRadius: 11, backgroundColor: colors.panelRaised, color: colors.text, paddingHorizontal: 11, fontSize: 11, outlineStyle: 'none' } as any, sendButton: { width: 39, height: 39, borderRadius: 11, backgroundColor: colors.lime, alignItems: 'center', justifyContent: 'center' },

  stars: { flexDirection: 'row', gap: 4 },
  profileHero: { backgroundColor: colors.panel, borderWidth: 1, borderColor: colors.line, borderRadius: radius.xl, overflow: 'hidden', marginBottom: 28 },
  cover: { height: 190, overflow: 'hidden' },
  coverOrbOne: { position: 'absolute', width: 260, height: 260, borderRadius: 130, backgroundColor: 'rgba(200,255,90,0.08)', right: 80, top: -120 },
  coverOrbTwo: { position: 'absolute', width: 190, height: 190, borderRadius: 95, backgroundColor: 'rgba(111,168,255,0.12)', left: 90, bottom: -130 },
  editProfileButton: { position: 'absolute', right: 20, top: 20 },
  profileIdentity: { padding: 22, paddingTop: 18, flexDirection: 'row', alignItems: 'center', gap: 18, flexWrap: 'wrap' },
  profileAvatar: { marginTop: -68 },
  profileCopy: { flex: 1, minWidth: 240 },
  profileName: { color: colors.text, fontSize: 24, fontWeight: '900' },
  profileHandle: { color: colors.textMuted, fontSize: 11, fontWeight: '700', marginTop: 4 },
  profileBio: { color: colors.textMuted, fontSize: 12, lineHeight: 18, marginTop: 9, maxWidth: 550 },
  profileStats: { flexDirection: 'row', gap: 15, alignItems: 'center' },

  profileGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 24 },
  profileMain: { flex: 1.5, minWidth: 310 },
  profileMainFull: { width: '100%', maxWidth: 980, alignSelf: 'center' },
  profileSide: { flex: 0.7, minWidth: 285 },
  reviewsList: { gap: 12, marginBottom: 30 },
  reviewCard: { backgroundColor: colors.panel, borderWidth: 1, borderColor: colors.line, borderRadius: radius.lg, padding: 12, flexDirection: 'row', gap: 14 },
  reviewPoster: { width: 92, minHeight: 125 },
  reviewPosterRadius: { borderRadius: 15 },
  reviewContent: { flex: 1, paddingVertical: 4 },
  reviewTop: { flexDirection: 'row', justifyContent: 'space-between', gap: 10, flexWrap: 'wrap' },
  reviewTitle: { color: colors.text, fontSize: 15, fontWeight: '900' },
  reviewDate: { color: colors.textDim, fontSize: 9, marginTop: 3 },
  reviewText: { color: colors.textMuted, fontSize: 11, lineHeight: 17, marginTop: 11 },
  reviewLikes: { flexDirection: 'row', alignItems: 'center', gap: 5, marginTop: 11 },
  reviewLikesText: { color: colors.textDim, fontSize: 9 },
  connectionsCard: { backgroundColor: colors.panel, borderWidth: 1, borderColor: colors.line, borderRadius: radius.lg, padding: 14 },
  connectionRow: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: colors.line },
  connectionCopy: { flex: 1 },
  connectionName: { color: colors.text, fontSize: 11, fontWeight: '900' },
  connectionStatus: { color: colors.textDim, fontSize: 9, marginTop: 3 },
  connectionStatusActive: { color: colors.success },
  connectionAction: { color: colors.lime, fontSize: 9, fontWeight: '900' },
  editAvatarRow: { flexDirection: 'row', alignItems: 'center', gap: 14, marginBottom: 15 },
  imageHint: { color: colors.textDim, fontSize: 9, marginTop: 6 },

  settingsGrid: { flexDirection: 'row', alignItems: 'flex-start', flexWrap: 'wrap', gap: 22 },
  settingsMain: { flex: 1.35, minWidth: 310, gap: 18 },
  settingsSide: { flex: 0.8, minWidth: 290, gap: 18 },
  settingsSection: { backgroundColor: colors.panel, borderWidth: 1, borderColor: colors.line, borderRadius: radius.lg, padding: 20 },
  settingsHelp: { color: colors.textMuted, fontSize: 11, lineHeight: 17, marginTop: -6, marginBottom: 14 },
  accountSettingCard: { minHeight: 76, borderRadius: radius.md, backgroundColor: colors.inkSoft, borderWidth: 1, borderColor: colors.line, flexDirection: 'row', alignItems: 'center', gap: 13, padding: 11 },
  accountSettingCopy: { flex: 1 },
  accountSettingName: { color: colors.text, fontSize: 14, fontWeight: '900' },
  accountSettingHandle: { color: colors.textMuted, fontSize: 10, marginTop: 4 },
  settingsCountryGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  settingsCountry: { width: '48%', minWidth: 160, flexGrow: 1, minHeight: 52, borderRadius: 13, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.inkSoft, paddingHorizontal: 11, flexDirection: 'row', alignItems: 'center', gap: 9 },
  settingsCountryActive: { borderColor: colors.lime, backgroundColor: 'rgba(200,255,90,0.06)' },
  countryCodeBox: { width: 30, height: 30, borderRadius: 9, backgroundColor: colors.panelRaised, alignItems: 'center', justifyContent: 'center' },
  countryCodeText: { color: colors.lime, fontSize: 9, fontWeight: '900' },
  settingsCountryName: { color: colors.textMuted, fontSize: 11, fontWeight: '800', flex: 1 },
  settingsCountryNameActive: { color: colors.text },
  settingToggleRow: { minHeight: 70, flexDirection: 'row', alignItems: 'center', gap: 11, borderTopWidth: 1, borderTopColor: colors.line, paddingVertical: 11 },
  settingRowIcon: { width: 38, height: 38, borderRadius: 12, backgroundColor: 'rgba(200,255,90,0.08)', alignItems: 'center', justifyContent: 'center' },
  settingRowCopy: { flex: 1, minWidth: 0 },
  settingRowTitle: { color: colors.text, fontSize: 12, fontWeight: '900' },
  settingRowDescription: { color: colors.textMuted, fontSize: 9, lineHeight: 14, marginTop: 3 },
  dataActions: { gap: 8, marginTop: 12 },
  securityNote: { flexDirection: 'row', alignItems: 'flex-start', gap: 9, backgroundColor: 'rgba(98,217,159,0.07)', borderRadius: 12, padding: 11, marginBottom: 12 },
  securityNoteText: { color: colors.textMuted, fontSize: 9, lineHeight: 14, flex: 1 },
  settingsLogout: { marginTop: 9 },

  detailBackdrop: { flex: 1, backgroundColor: 'rgba(0,0,0,0.78)', justifyContent: 'flex-end', alignItems: 'center' },
  detailModal: { width: '100%', maxWidth: 760, maxHeight: '94%', backgroundColor: colors.panel, borderTopLeftRadius: radius.xl, borderTopRightRadius: radius.xl, overflow: 'hidden', borderWidth: 1, borderColor: colors.line },
  detailHero: { height: 360 },
  detailHeroRadius: { borderTopLeftRadius: radius.xl, borderTopRightRadius: radius.xl },
  detailGradient: { flex: 1, justifyContent: 'flex-end', padding: 24 },
  detailClose: { position: 'absolute', right: 18, top: 18 },
  detailHeroCopy: { maxWidth: 600 },
  detailMatch: { color: colors.lime, fontSize: 10, fontWeight: '900', letterSpacing: 1.5 },
  detailTitle: { color: colors.white, fontSize: 40, lineHeight: 44, fontWeight: '900', letterSpacing: -1.5, marginTop: 6 },
  detailSubtitle: { color: '#E5E9F0', fontSize: 14, fontWeight: '700', marginTop: 5 },
  detailBody: { padding: 24 },
  detailMeta: { flexDirection: 'row', alignItems: 'center', flexWrap: 'wrap', gap: 11 },
  detailMetaText: { color: colors.textMuted, fontSize: 11, fontWeight: '700' },
  detailScore: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  genreRow: { flexDirection: 'row', gap: 7, flexWrap: 'wrap', marginTop: 12 },
  detailSynopsis: { color: colors.text, fontSize: 14, lineHeight: 22, marginTop: 18 },
  reasonCard: { flexDirection: 'row', gap: 12, backgroundColor: 'rgba(200,255,90,0.07)', borderWidth: 1, borderColor: 'rgba(200,255,90,0.16)', borderRadius: radius.md, padding: 14, marginTop: 18 },
  reasonIcon: { width: 37, height: 37, borderRadius: 12, backgroundColor: colors.lime, alignItems: 'center', justifyContent: 'center' },
  reasonCopy: { flex: 1 },
  reasonTitle: { color: colors.text, fontSize: 12, fontWeight: '900' },
  reasonText: { color: colors.textMuted, fontSize: 10, lineHeight: 16, marginTop: 3 },
  availableRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginTop: 18 },
  availableLabel: { color: colors.textMuted, fontSize: 11, fontWeight: '800', marginRight: 3 },
  detailActions: { flexDirection: 'row', gap: 10, marginTop: 20 },
  detailAction: { flex: 1 },
  reviewComposer: { borderTopWidth: 1, borderTopColor: colors.line, marginTop: 24, paddingTop: 20 },
  reviewComposerTop: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 },
  reviewComposerTitle: { color: colors.text, fontSize: 18, fontWeight: '900' },
  reviewComposerSub: { color: colors.textMuted, fontSize: 10, marginTop: 3 },
  reviewForm: { marginTop: 18 },

  notificationBackdrop: { flex: 1, backgroundColor: 'rgba(0,0,0,0.55)', alignItems: 'flex-end', paddingTop: 66, paddingRight: 18 },
  notificationPanel: { width: '92%', maxWidth: 390, backgroundColor: colors.panel, borderWidth: 1, borderColor: colors.line, borderRadius: radius.lg, padding: 17, ...shadow },
  notificationHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 10 },
  notificationTitle: { color: colors.text, fontSize: 19, fontWeight: '900' },
  notificationSubtitle: { color: colors.textDim, fontSize: 9, fontWeight: '700', marginTop: 3 },
  notificationList: { maxHeight: 440 },
  notificationRow: { minHeight: 70, flexDirection: 'row', alignItems: 'center', gap: 10, borderTopWidth: 1, borderTopColor: colors.line, paddingVertical: 8 },
  notificationRowRead: { opacity: 0.58 },
  notificationIcon: { width: 38, height: 38, borderRadius: 12, alignItems: 'center', justifyContent: 'center' },
  notificationCopy: { flex: 1 },
  notificationItemTitle: { color: colors.text, fontSize: 11, fontWeight: '900' },
  notificationItemText: { color: colors.textMuted, fontSize: 9, marginTop: 4 },
  unreadDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: colors.coral },

});
