import { ContentItem, ForumTopic, Friend, Provider } from './types';

export const providers: Provider[] = [
  { id: 'netflix', name: 'Netflix', shortName: 'N', color: '#E50914', foreground: '#FFFFFF' },
  { id: 'max', name: 'Max', shortName: 'max', color: '#6A3DFF', foreground: '#FFFFFF' },
  { id: 'disney', name: 'Disney+', shortName: 'D+', color: '#0B65D8', foreground: '#FFFFFF' },
  { id: 'crunchyroll', name: 'Crunchyroll', shortName: 'C', color: '#F47521', foreground: '#FFFFFF' },
  { id: 'prime', name: 'Prime Video', shortName: 'prime', color: '#1399FF', foreground: '#FFFFFF' },
];

export const countries = [
  { code: 'MX', name: 'México', flag: '🇲🇽' },
  { code: 'ES', name: 'España', flag: '🇪🇸' },
  { code: 'AR', name: 'Argentina', flag: '🇦🇷' },
  { code: 'CO', name: 'Colombia', flag: '🇨🇴' },
  { code: 'CL', name: 'Chile', flag: '🇨🇱' },
  { code: 'US', name: 'Estados Unidos', flag: '🇺🇸' },
];

export const genres = ['Ciencia ficción', 'Drama', 'Comedia', 'Terror', 'Anime', 'Documental', 'Misterio', 'Romance'];

export const catalogue: ContentItem[] = [
  {
    id: 'signal-noir',
    title: 'Señal nocturna',
    subtitle: 'Una llamada. Dos épocas. Ninguna salida.',
    type: 'Película',
    year: 2025,
    duration: '1 h 58 min',
    maturity: '16+',
    score: 4.7,
    match: 96,
    genres: ['Misterio', 'Ciencia ficción'],
    providers: ['netflix'],
    countries: ['MX', 'ES', 'AR', 'CO'],
    image: require('../../assets/posters/signal-nocturna.png'),
    palette: ['#0D1B2A', '#284B63'],
    synopsis: 'Una operadora de radio descubre que puede hablar con una desconocida atrapada veinticinco años en el pasado. Cada respuesta altera su propia noche.',
    reason: 'Porque terminaste tres thrillers de ritmo lento y sueles calificar mejor las historias con paradojas temporales.',
    friendSignal: 'A Sofía y Mateo también les gustó',
  },
  {
    id: 'after-the-rain',
    title: 'Después de la lluvia',
    subtitle: 'Volver también es una forma de avanzar.',
    type: 'Serie',
    year: 2026,
    duration: '8 episodios',
    maturity: '13+',
    score: 4.5,
    match: 92,
    genres: ['Drama', 'Romance'],
    providers: ['max'],
    countries: ['MX', 'ES', 'CO', 'CL'],
    image: require('../../assets/posters/despues-de-la-lluvia.png'),
    palette: ['#183A37', '#DDA15E'],
    synopsis: 'Dos antiguos amigos regresan al pueblo costero que juraron abandonar y encuentran un archivo de cartas que cambia lo que recuerdan.',
    reason: 'Tiene el tipo de drama íntimo que guardas para el fin de semana, con episodios cortos y una historia cerrada.',
    friendSignal: 'Valeria la calificó con 5 estrellas',
  },
  {
    id: 'orbit-9',
    title: 'Órbita nueve',
    subtitle: 'La misión terminó. La tripulación no.',
    type: 'Serie',
    year: 2025,
    duration: '10 episodios',
    maturity: '16+',
    score: 4.8,
    match: 89,
    genres: ['Ciencia ficción', 'Drama'],
    providers: ['prime'],
    countries: ['MX', 'AR', 'CO', 'US'],
    image: require('../../assets/posters/orbita-nueve.png'),
    palette: ['#121A2F', '#6D597A'],
    synopsis: 'Al despertar de una misión fallida, nueve astronautas reciben mensajes firmados por versiones futuras de ellos mismos.',
    reason: 'Coincide con tu gusto por equipos imperfectos, conspiraciones contenidas y finales que invitan a debatir.',
    friendSignal: '4 personas de tu círculo quieren verla',
  },
  {
    id: 'paper-gods',
    title: 'Dioses de papel',
    subtitle: 'Toda leyenda comienza con una mentira.',
    type: 'Anime',
    year: 2026,
    duration: '12 episodios',
    maturity: '13+',
    score: 4.6,
    match: 87,
    genres: ['Anime', 'Fantasía'],
    providers: ['crunchyroll'],
    countries: ['MX', 'ES', 'AR', 'CO', 'CL', 'US'],
    image: require('../../assets/posters/dioses-de-papel.png'),
    palette: ['#2B193D', '#C8553D'],
    synopsis: 'Una aprendiz de restauración libera a una deidad olvidada al reparar un libro que debía permanecer incompleto.',
    reason: 'Tus favoritos combinan mundos fantásticos con protagonistas que resuelven problemas usando ingenio, no fuerza.',
    friendSignal: 'Diego va en el episodio 4',
  },
  {
    id: 'the-last-lantern',
    title: 'La última linterna',
    subtitle: 'La ciudad duerme. Ella sigue buscando.',
    type: 'Película',
    year: 2024,
    duration: '2 h 06 min',
    maturity: '16+',
    score: 4.4,
    match: 84,
    genres: ['Misterio', 'Drama'],
    providers: ['disney'],
    countries: ['MX', 'ES', 'AR', 'CL'],
    image: require('../../assets/posters/la-ultima-linterna.png'),
    palette: ['#18212E', '#B08968'],
    synopsis: 'Una archivista sigue un mapa de luces encendidas durante el gran apagón y descubre la historia secreta de su familia.',
    reason: 'Comparte la fotografía contemplativa de dos películas que reseñaste positivamente el mes pasado.',
    friendSignal: 'Sofía escribió una reseña sin spoilers',
  },
];

export const initialTopics: ForumTopic[] = [
  {
    id: 't1', kind: 'discussion', title: 'El final de Señal nocturna: ¿bucle o decisión?',
    body: 'Creo que la última llamada ocurre antes de la primera escena, pero la taza cambia de lugar. ¿Alguien más lo interpretó así?',
    author: 'Sofía R.', initials: 'SR', time: 'Hace 18 min', tags: ['Teorías', 'Con spoilers'], replies: 34, likes: 87,
  },
  {
    id: 't2', kind: 'discussion', title: 'Series cortas que sí cierran bien su historia',
    body: 'Busco temporadas de 6 a 10 episodios que no terminen en cliffhanger. Compartan sus favoritas.',
    author: 'Mateo G.', initials: 'MG', time: 'Hace 1 h', tags: ['Recomendaciones', 'Series'], replies: 51, likes: 123,
  },
  {
    id: 't3', kind: 'identify', title: 'Película de una estación de tren que aparecía sólo de noche',
    body: 'La vi de niño. Una mujer esperaba un tren, el reloj siempre marcaba las 3:17 y creo que era europea. No era de terror.',
    author: 'Nora P.', initials: 'NP', time: 'Hace 42 min', tags: ['Ayúdame a encontrarla', 'Años 2000'], replies: 12, likes: 28, solved: false,
  },
  {
    id: 't4', kind: 'identify', title: 'Animación sobre un niño que coleccionaba sonidos',
    body: 'Era una película animada en 2D. Guardaba sonidos en frascos y al final liberaba una tormenta dentro de una biblioteca.',
    author: 'Diego L.', initials: 'DL', time: 'Ayer', tags: ['Resuelto', 'Animación'], replies: 19, likes: 46, solved: true,
  },
];

export const initialFriends: Friend[] = [
  { id: 'f1', name: 'Sofía Ramírez', handle: '@sofiaframes', initials: 'SR', color: '#9B7EDE', compatibility: 94, status: 'Viendo Órbita nueve', online: true },
  { id: 'f2', name: 'Mateo García', handle: '@mateocine', initials: 'MG', color: '#3BA99C', compatibility: 88, status: 'Disponible para una sala', online: true },
  { id: 'f3', name: 'Valeria Cruz', handle: '@valecuenta', initials: 'VC', color: '#E76F51', compatibility: 81, status: 'Vio Después de la lluvia', online: false },
  { id: 'f4', name: 'Diego Luna', handle: '@diegoroll', initials: 'DL', color: '#457B9D', compatibility: 76, status: 'En episodio 4', online: false },
];
